/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}

//
// Function: itemClicked()
// Called when an item from the items list is selected to navigate to the detail view
//
function itemClicked(event)
{
    var list = document.getElementById("list").object;
    var browser = document.getElementById('browser').object;
    var selectedObjects = list.selectedObjects();
    
    if (selectedObjects && (1 == selectedObjects.length)){
        // The Browser's goForward method is used to make the browser push down to a new level.
        // Going back to previous levels is handled automatically.
        var name = selectedObjects[0].valueForKey("name");
        if(name == "Current Images") {
            browser.goForward(document.getElementById('cImageSelectSource'), selectedObjects[0].valueForKey("name"));
        }
        else {
            browser.goForward(document.getElementById('detailLevel'), "Detail");
        }
    }    
}


function testGotoDetail(event) {
    var browser = document.getElementById('browser').object;
    browser.goForward(document.getElementById('detailLevel'), "Detail");
}

function testGotoImage(event) {
    window.location = "http://solarmonitor.org/data/20100518/pngs/seit/seit_00171_fd_20100518_010014.png";
    
}
function testGotoMovie(event) {
    window.location = "http://10.0.2.1/seit.m4v";
}